"""Definitional / slow reference oracles for Lyndon-word tests."""

from .word_oracle import (
    is_lyndon,
    packed,
    is_packed,
    standard_factorization,
    standard_bracketing,
    lyndon_count,
    all_words_of_length,
    all_words_upto_length,
    mobius,
)
from .nc_polynomial_oracle import (
    normalize,
    add,
    neg,
    sub,
    mul,
    degree,
    monomial,
    from_word,
    get_coefficient,
    P,
    terms_from_str_map,
    str_map_from_terms,
)

__all__ = [
    "is_lyndon",
    "packed",
    "is_packed",
    "standard_factorization",
    "standard_bracketing",
    "lyndon_count",
    "all_words_of_length",
    "all_words_upto_length",
    "mobius",
    "normalize",
    "add",
    "neg",
    "sub",
    "mul",
    "degree",
    "monomial",
    "from_word",
    "get_coefficient",
    "P",
    "terms_from_str_map",
    "str_map_from_terms",
]
